-- SQL Script for Supabase SQL Editor
-- This script creates the schema for the Gold Girvi Management Software

-- 1. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    mobile_number TEXT NOT NULL,
    nominee_name TEXT,
    full_address TEXT,
    aadhaar_number TEXT,
    pan_number TEXT,
    portal_user_id TEXT UNIQUE,
    portal_password TEXT,
    photo_url TEXT,
    aadhaar_card_url TEXT,
    pan_card_url TEXT,
    signature_url TEXT,
    nominee_id_proof_url TEXT,
    other_attachments TEXT, -- JSON string
    status TEXT DEFAULT 'active', -- active, verified, blacklisted
    kyc_status TEXT DEFAULT 'pending',
    registration_complete BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Loans Table
CREATE TABLE IF NOT EXISTS loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
    loan_number TEXT UNIQUE NOT NULL,
    loan_amount DECIMAL(15, 2) NOT NULL,
    interest_rate DECIMAL(5, 2) NOT NULL,
    interest_type TEXT DEFAULT 'simple', -- simple, compound
    interest_cycle TEXT DEFAULT 'Monthly', -- Monthly, Daily, Weekly
    penalty_rate DECIMAL(5, 2) DEFAULT 0,
    start_date DATE NOT NULL DEFAULT CURRENT_DATE,
    maturity_date DATE NOT NULL,
    disbursement_mode TEXT DEFAULT 'Cash',
    disbursement_transaction_id TEXT,
    status TEXT DEFAULT 'active', -- active, closed, defaulted
    closure_requested BOOLEAN DEFAULT false,
    remarks TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Items Table (Pledged Items)
CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id BIGINT REFERENCES loans(id) ON DELETE CASCADE,
    type TEXT NOT NULL, -- Gold Ornament, Silver, etc.
    purity TEXT, -- 22K, 24K, etc.
    gross_weight DECIMAL(10, 3) NOT NULL,
    net_weight DECIMAL(10, 3) NOT NULL,
    wastage DECIMAL(10, 3) DEFAULT 0,
    market_rate DECIMAL(15, 2),
    valuation DECIMAL(15, 2) NOT NULL,
    packet_number TEXT,
    locker_location TEXT,
    status TEXT DEFAULT 'pledged', -- pledged, released, auctioned
    photos TEXT, -- JSON string of URLs
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Payments Table
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id BIGINT REFERENCES loans(id) ON DELETE CASCADE,
    amount DECIMAL(15, 2) NOT NULL,
    payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    payment_mode TEXT NOT NULL, -- Cash, UPI, Bank Transfer
    payment_type TEXT NOT NULL, -- interest, principal, penalty, full_settlement
    transaction_id TEXT,
    remarks TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Migration/Repair: Ensure column names match the code
DO $$ 
BEGIN 
  -- Handle payments table: amount_received -> amount
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='payments' AND column_name='amount_received') THEN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='payments' AND column_name='amount') THEN
      ALTER TABLE payments RENAME COLUMN amount_received TO amount;
    ELSE
      -- Both exist: Copy data to 'amount' if it's empty/zero, then drop the old column
      UPDATE payments SET amount = amount_received WHERE amount = 0 OR amount IS NULL;
      ALTER TABLE payments DROP COLUMN amount_received;
    END IF;
  END IF;
  
  -- Handle items table: item_type -> type
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='items' AND column_name='item_type') THEN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='items' AND column_name='type') THEN
      ALTER TABLE items RENAME COLUMN item_type TO type;
    ELSE
      -- Both exist: Copy data to 'type' if it's empty, then drop the old column
      UPDATE items SET type = item_type WHERE type IS NULL OR type = '';
      ALTER TABLE items DROP COLUMN item_type;
    END IF;
  END IF;
END $$;

-- 5. Top-ups Table (Additional Loan Amount)
CREATE TABLE IF NOT EXISTS top_ups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id BIGINT REFERENCES loans(id) ON DELETE CASCADE,
    amount DECIMAL(15, 2) NOT NULL,
    top_up_date DATE NOT NULL DEFAULT CURRENT_DATE,
    remarks TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Settings Table
CREATE TABLE IF NOT EXISTS settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name TEXT NOT NULL,
    shop_address TEXT,
    shop_mobile TEXT,
    default_interest_rate DECIMAL(5, 2) DEFAULT 2.0,
    default_penalty_rate DECIMAL(5, 2) DEFAULT 1.0,
    currency_symbol TEXT DEFAULT '₹',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS (Row Level Security)
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE items ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE top_ups ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Create Public Access Policies (For Demo/Development)
DROP POLICY IF EXISTS "Public Access" ON customers;
CREATE POLICY "Public Access" ON customers FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Access" ON loans;
CREATE POLICY "Public Access" ON loans FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Access" ON items;
CREATE POLICY "Public Access" ON items FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Access" ON payments;
CREATE POLICY "Public Access" ON payments FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Access" ON top_ups;
CREATE POLICY "Public Access" ON top_ups FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Access" ON settings;
CREATE POLICY "Public Access" ON settings FOR ALL USING (true) WITH CHECK (true);
